# Generated by Django 3.1.5 on 2021-02-16 17:02

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.IntegerField(verbose_name='created_by')),
            ],
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_group', models.CharField(max_length=100, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.IntegerField(verbose_name='created_by')),
            ],
        ),
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.IntegerField(verbose_name='created_by')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='choose_classgroup', to='master.classgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trust_name', models.CharField(max_length=60, verbose_name='Trust Name')),
                ('institution_name', models.CharField(max_length=60, verbose_name='Institution Name')),
                ('address1', models.CharField(max_length=300, verbose_name='Address1')),
                ('address2', models.CharField(max_length=300, verbose_name='Address2')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('administrator', models.CharField(max_length=300, verbose_name='Administrator')),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.IntegerField(verbose_name='created by')),
            ],
        ),
        migrations.CreateModel(
            name='RoomManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.IntegerField(verbose_name='created_by')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='choose_classname', to='master.classname')),
            ],
        ),
        migrations.CreateModel(
            name='Caste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caste', models.CharField(max_length=100, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.IntegerField(verbose_name='created_by')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='choose_category', to='master.category')),
            ],
        ),
    ]
