# Generated by Django 3.1.5 on 2021-01-17 16:37

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_classname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CreateClassGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_classgroup', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trustName', models.CharField(max_length=60, verbose_name='Trust Name')),
                ('institutionName', models.CharField(max_length=60, verbose_name='Institution Name')),
                ('address1', models.CharField(max_length=300, verbose_name='Address1')),
                ('address2', models.CharField(max_length=300, verbose_name='Address2')),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('administrator', models.CharField(max_length=300, verbose_name='Administrator')),
                ('mobileNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(max_length=60, verbose_name='created_by')),
            ],
        ),
        migrations.CreateModel(
            name='RoomManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CreateSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_sectionname', models.CharField(max_length=100)),
                ('choose_classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choose_classname', to='master.createclass')),
            ],
        ),
        migrations.AddField(
            model_name='createclass',
            name='choose_classgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choose_classgroup', to='master.createclassgroup'),
        ),
    ]
