# Generated by Django 3.1.5 on 2021-03-04 14:26

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caste',
            name='caste',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z() ]+$', 'only valid caste name is required')]),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9-/() ]+$', 'only valid category is required')]),
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='class_group',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z- ]+$', 'only valid class group is required')]),
        ),
        migrations.AlterField(
            model_name='classname',
            name='class_name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9- ]+$', 'only valid class name is required')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address1',
            field=models.CharField(max_length=300, validators=[django.core.validators.RegexValidator('^(\\w *\\s*[\\  # \\-\\,\\/\\.\\(\\)\\&]*)+$', 'only valid address is required')], verbose_name='Address1'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address2',
            field=models.CharField(max_length=300, validators=[django.core.validators.RegexValidator('^(\\w *\\s*[\\  # \\-\\,\\/\\.\\(\\)\\&]*)+$', 'only valid address is required')], verbose_name='Address2'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='institution_name',
            field=models.CharField(max_length=60, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$', 'only valid trust name is required')], verbose_name='Institution Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='trust_name',
            field=models.CharField(max_length=60, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$', 'only valid trust name is required')], verbose_name='Trust Name'),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$', 'only valid section name is required')]),
        ),
    ]
