# Generated by Django 3.1.5 on 2021-03-08 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20210308_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='academic_end_year',
            field=models.IntegerField(max_length=4, null=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'only valid academic_year is required')]),
        ),
        migrations.AddField(
            model_name='profile',
            name='academic_start_year',
            field=models.IntegerField(max_length=4, null=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'only valid academic_year is required')]),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$', 'only valid section name is required')]),
        ),
    ]
