# Generated by Django 3.1.5 on 2021-01-26 15:25

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20210121_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_group', models.CharField(max_length=100, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.IntegerField(verbose_name='created_by')),
            ],
        ),
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.IntegerField(verbose_name='created_by')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choose_classgroup', to='master.classgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trust_name', models.CharField(max_length=60, verbose_name='Trust Name')),
                ('institution_name', models.CharField(max_length=60, verbose_name='Institution Name')),
                ('address1', models.CharField(max_length=300, verbose_name='Address1')),
                ('address2', models.CharField(max_length=300, verbose_name='Address2')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('administrator', models.CharField(max_length=300, verbose_name='Administrator')),
                ('mobil_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.IntegerField(verbose_name='created by')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.IntegerField(verbose_name='created_by')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choose_classname', to='master.classname')),
            ],
        ),
        migrations.RemoveField(
            model_name='createclass',
            name='choose_classgroup',
        ),
        migrations.RemoveField(
            model_name='createsection',
            name='choose_classname',
        ),
        migrations.DeleteModel(
            name='ProfileRegister',
        ),
        migrations.DeleteModel(
            name='CreateClass',
        ),
        migrations.DeleteModel(
            name='CreateClassGroup',
        ),
        migrations.DeleteModel(
            name='CreateSection',
        ),
    ]
