# Generated by Django 3.1.5 on 2021-03-08 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20210308_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='academic_end_year',
            field=models.IntegerField(null=True, validators=[django.core.validators.RegexValidator('^[0-9]{4}+$', 'only valid academic_year is required')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='academic_start_year',
            field=models.IntegerField(null=True, validators=[django.core.validators.RegexValidator('^[0-9]{4}+$', 'only valid academic_year is required')]),
        ),
    ]
