# Generated by Django 3.1.5 on 2021-02-02 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_auto_20210127_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.IntegerField(verbose_name='created_by')),
            ],
        ),
        migrations.AlterField(
            model_name='classname',
            name='class_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='choose_classgroup', to='master.classgroup'),
        ),
        migrations.AlterField(
            model_name='section',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='choose_classname', to='master.classname'),
        ),
        migrations.CreateModel(
            name='Caste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caste', models.CharField(max_length=100, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.IntegerField(verbose_name='created_by')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='choose_category', to='master.category')),
            ],
        ),
    ]
