# Generated by Django 3.1.5 on 2021-03-06 07:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preadmission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_photo', models.ImageField(null=True, upload_to=student.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Photo')),
                ('birth_certificate', models.ImageField(null=True, upload_to=student.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Photo')),
                ('tc', models.ImageField(null=True, upload_to=student.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Photo')),
                ('other_document', models.ImageField(null=True, upload_to=student.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Photo')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded On')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='preadmission.application')),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='student.student')),
            ],
        ),
    ]
