# Generated by Django 3.1.5 on 2021-03-06 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='application',
        ),
    ]
