# Generated by Django 3.1.5 on 2021-03-09 14:18

import django.core.validators
from django.db import migrations
import private_storage.fields
import private_storage.storage.files
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_document_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='photo',
            field=private_storage.fields.PrivateFileField(null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=student.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Photo'),
        ),
    ]
