# Generated by Django 3.1.4 on 2021-01-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210120_0648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdocument',
            old_name='application_number',
            new_name='application_id',
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='birth_certificate',
            field=models.ImageField(null=True, upload_to='uploads/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='student_photo',
            field=models.ImageField(height_field=300, null=True, upload_to='uploads/', verbose_name='Photo', width_field=300),
        ),
    ]
