# Generated by Django 3.1.5 on 2021-03-11 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_document_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='photo',
        ),
    ]
