# Generated by Django 3.1.4 on 2021-01-21 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20210121_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdocument',
            name='tc',
            field=models.ImageField(null=True, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Photo'),
        ),
    ]
