# Generated by Django 3.1.4 on 2021-01-21 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210121_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdocument',
            name='other_document_1',
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='birth_certificate',
            field=models.ImageField(null=True, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='other_document',
            field=models.ImageField(null=True, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='student_photo',
            field=models.ImageField(null=True, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='tc',
            field=models.ImageField(null=True, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Photo'),
        ),
    ]
