# Generated by Django 3.1.4 on 2021-01-21 11:08

import django.core.validators
from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20210121_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdocument',
            name='birth_certificate',
            field=models.ImageField(null=True, upload_to=student.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='other_document',
            field=models.ImageField(null=True, upload_to=student.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='student_photo',
            field=models.ImageField(null=True, upload_to=student.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='tc',
            field=models.ImageField(null=True, upload_to=student.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Photo'),
        ),
    ]
