# Generated by Django 3.1.4 on 2021-01-21 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20210121_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdocument',
            old_name='application_id',
            new_name='application',
        ),
        migrations.RenameField(
            model_name='studentdocument',
            old_name='student_id',
            new_name='student',
        ),
    ]
