from django.db import models

class Application(models.Model):
    student_name = models.CharField('Student Name', max_length=60)
    dob = models.DateField('Date of Birth')
    class_name = models.PositiveIntegerField('Class')
    father_name =  models.CharField('Father name', max_length=60)
    father_mobile = models.CharField('Father Mobile Number', max_length=12, null=True, blank=True)
    father_email = models.EmailField('Father Email Address', null=True, blank=True)
    father_qualification = models.CharField('Father Qualification', max_length=20, null=True, blank=True)
    father_occupation = models.CharField('Father Occupation', max_length=20, null=True, blank=True)
    father_annual_income = models.DecimalField('Father Annual Income', max_digits=10, decimal_places=2, null=True, blank=True)
    mother_name =  models.CharField('Mother name', max_length=60)
    mother_mobile = models.CharField('Mother Mobile Number', max_length=12, null=True, blank=True)
    mother_email = models.EmailField('Mother Email Address', null=True, blank=True)
    mother_qualification = models.CharField('Mother Qualification', max_length=20, null=True, blank=True)
    mother_occupation = models.CharField('Mother Occupation', max_length=20, null=True, blank=True)
    mother_annual_income = models.DecimalField('Mother Annual Income', max_digits=10, decimal_places=2, null=True, blank=True)
    address = models.TextField('Address', max_length=600)
    post_code = models.IntegerField('Post Code')
    guardian_name =  models.CharField('Guardian name', max_length=60, null=True, blank=True)
    guardian_mobile = models.CharField('Guardian Mobile Number', max_length=12, null=True, blank=True)
    guardian_email = models.EmailField('Guardian Email Address', null=True, blank=True)
    guardian_address = models.TextField('Guardian Address', max_length=600, null=True, blank=True)
    guardian_post_code = models.IntegerField('Guardian Post Code', null=True, blank=True)
    previous_school = models.CharField('Previous School Name', max_length=200, null=True, blank=True)
    primary_contact_person_choice = [('father','Father'),('mother','Mother'),('guardian','Guardian')]
    primary_contact_person = models.CharField(choices=primary_contact_person_choice, max_length=10)
    query = models.TextField("Query", max_length=2000, blank=True)
    is_verified = models.BooleanField('Is Verified', default=0)
    is_applied = models.BooleanField('Is Applied', default=0)
    reference_number = models.CharField('Refrence Number', max_length=50, null=True)
    created_by = models.IntegerField('Created By', default=0)
    created_on = models.DateTimeField(auto_now_add=True, null=True)
