# Generated by Django 3.1.4 on 2021-01-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Module Name')),
                ('description', models.CharField(max_length=150, verbose_name='Module Description')),
                ('rank', models.IntegerField(verbose_name='Priority')),
                ('color', models.CharField(max_length=60, null=True, verbose_name='Module Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='IsActive')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
