# Generated by Django 3.1.4 on 2021-01-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='is_active',
            field=models.BooleanField(default=0, verbose_name='IsActive'),
        ),
    ]
