# Generated by Django 3.1.4 on 2021-01-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210105_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
