# Generated by Django 3.1.4 on 2021-01-08 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_module_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Module',
        ),
    ]
