from django.urls import path, include
from .views import ProfileViewSet, ClassGroupViewset, ClassNameViewset, SectionViewset, CategoryViewset, CasteViewset

urlpatterns = [
    path('profile/list/', ProfileViewSet.as_view({'get':'list'}), name='list_profile'),
    path('profile/detail/<pk>/', ProfileViewSet.as_view({'get':'retrieve'}), name='profile'),
    path('profile/create/', ProfileViewSet.as_view({'post':'create'}), name='create_profile'),
    path('profile/update/<pk>/', ProfileViewSet.as_view({'put':'update'}), name='update_profile'),
    path('profile/delete/<pk>/', ProfileViewSet.as_view({'delete':'destroy'}), name='delete_profile'),
    path('class/group/create/', ClassGroupViewset.as_view({'post':'create'}), name='create_class_group'),
    path('class/group/list/', ClassGroupViewset.as_view({'get':'list'}), name='list_class_group'),
    path('class/group/detail/<pk>/', ClassGroupViewset.as_view({'get':'retrieve'}), name='detail_class_group'),
    path('class/group/update/<pk>/', ClassGroupViewset.as_view({'put':'update'}), name='update_class_group'),
    path('class/group/delete/<pk>/', ClassGroupViewset.as_view({'delete':'destroy'}), name='delete_class_group'),
    path('class/name/create/', ClassNameViewset.as_view({'post':'create'}), name='create_class_name'),
    path('class/name/list/', ClassNameViewset.as_view({'get':'list'}), name='list_class_name'),
    path('class/name/detail/<pk>/', ClassNameViewset.as_view({'get':'retrieve'}), name='detail_class_name'),
    path('class/name/update/<pk>/', ClassNameViewset.as_view({'put':'update'}), name='update_class_name'),
    path('class/name/delete/<pk>/', ClassNameViewset.as_view({'delete':'destroy'}), name='delete_class_name'),
    path('section/create/',SectionViewset.as_view({'post': 'create'}), name='create_class_section'),
    path('section/list/',SectionViewset.as_view({'get': 'list'}), name='list_class_section'),
    path('section/detail/<pk>/',SectionViewset.as_view({'get': 'retrieve'}), name='detail_class_section'),
    path('section/update/<pk>/',SectionViewset.as_view({'put': 'update'}), name='update_class_section'),
    path('section/delete/<pk>/',SectionViewset.as_view({'delete': 'destroy'}), name='delete_class_section'),
    path('category/create/',CategoryViewset.as_view({'post': 'create'}), name='create_category'),
    path('category/list/',CategoryViewset.as_view({'get': 'list'}), name='list_category'),
    path('category/detail/<pk>/',CategoryViewset.as_view({'get': 'retrieve'}), name='detail_category'),
    path('category/update/<pk>/',CategoryViewset.as_view({'put': 'update'}), name='update_category'),
    path('category/delete/<pk>/',CategoryViewset.as_view({'delete': 'destroy'}), name='delete_category'),
    path('caste/create/',CasteViewset.as_view({'post': 'create'}), name='create_caste'),
    path('caste/list/',CasteViewset.as_view({'get': 'list'}), name='list_caste'),
    path('caste/detail/<pk>/',CasteViewset.as_view({'get': 'retrieve'}), name='detail_caste'),
    path('caste/update/<pk>/',CasteViewset.as_view({'put': 'update'}), name='update_caste'),
    path('caste/delete/<pk>/',CasteViewset.as_view({'delete': 'destroy'}), name='delete_caste'),
]
