# Generated by Django 3.1.5 on 2021-03-06 07:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0002_auto_20210304_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_token', models.CharField(editable=False, max_length=250, unique=True, verbose_name='Application token')),
                ('first_name', models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(regex='^[a-zA-Z ]*$')], verbose_name='First Name')),
                ('last_name', models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(regex='^[a-zA-Z ]*$')], verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6, verbose_name='Gender')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('nationality', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nationality')),
                ('religion', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Religion')),
                ('father_name', models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(regex='^[a-zA-Z ]*$')], verbose_name='Father name')),
                ('father_mobile', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(regex='^[\\d]{10,12}$')], verbose_name='Father Mobile Number')),
                ('father_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Father Email Address')),
                ('father_qualification', models.CharField(blank=True, max_length=20, null=True, verbose_name='Father Qualification')),
                ('father_occupation', models.CharField(blank=True, max_length=20, null=True, verbose_name='Father Occupation')),
                ('father_annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Father Annual Income')),
                ('mother_name', models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(regex='^[a-zA-Z ]*$')], verbose_name='Mother name')),
                ('mother_mobile', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(regex='^[\\d]{10,12}$')], verbose_name='Mother Mobile Number')),
                ('mother_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Mother Email Address')),
                ('mother_qualification', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mother Qualification')),
                ('mother_occupation', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mother Occupation')),
                ('mother_annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Mother Annual Income')),
                ('current_address', models.TextField(verbose_name='Current Address')),
                ('permanent_address', models.TextField(blank=True, null=True, verbose_name='Permanent Address')),
                ('guardian_name', models.CharField(blank=True, max_length=60, null=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z ]*$')], verbose_name='Guardian name')),
                ('guardian_mobile', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(regex='^[\\d]{10,12}$')], verbose_name='Guardian Mobile Number')),
                ('guardian_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Guardian Email Address')),
                ('previous_school', models.CharField(blank=True, max_length=200, null=True, verbose_name='Previous School Name')),
                ('primary_contact_person', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian')], max_length=10)),
                ('query', models.TextField(blank=True, max_length=2000, verbose_name='Query')),
                ('is_verified', models.BooleanField(default=0, verbose_name='Is Verified')),
                ('is_applied', models.BooleanField(default=0, verbose_name='Is Applied')),
                ('reference_number', models.CharField(max_length=50, null=True, unique=True, verbose_name='Refrence Number')),
                ('created_by', models.IntegerField(default=0, verbose_name='Created By')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('caste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.caste')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.classname')),
            ],
        ),
    ]
