# Generated by Django 3.1.5 on 2021-03-06 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_document_application'),
        ('preadmission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='docs',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='student.document'),
            preserve_default=False,
        ),
    ]
