# Generated by Django 3.1.4 on 2021-01-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preadmission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_applied',
            field=models.BooleanField(default=0, verbose_name='Is Applied'),
        ),
    ]
