# Generated by Django 3.1.5 on 2021-03-02 14:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('preadmission', '0002_application_is_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='address',
        ),
        migrations.RemoveField(
            model_name='application',
            name='guardian_address',
        ),
        migrations.RemoveField(
            model_name='application',
            name='guardian_post_code',
        ),
        migrations.RemoveField(
            model_name='application',
            name='post_code',
        ),
        migrations.RemoveField(
            model_name='application',
            name='student_name',
        ),
        migrations.AddField(
            model_name='application',
            name='caste',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='master.caste'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='current_address',
            field=models.TextField(default=None, verbose_name='Current Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='first_name',
            field=models.CharField(default=None, max_length=60, validators=[django.core.validators.MinLengthValidator], verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default=None, max_length=6, verbose_name='Gender'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='last_name',
            field=models.CharField(default=None, max_length=60, validators=[django.core.validators.MinLengthValidator], verbose_name='Last Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='nationality',
            field=models.CharField(default=None, max_length=10, validators=[django.core.validators.MinLengthValidator], verbose_name='Nationality'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='permanent_address',
            field=models.TextField(blank=True, null=True, verbose_name='Permanent Address'),
        ),
        migrations.AddField(
            model_name='application',
            name='religion',
            field=models.CharField(default='', max_length=25, validators=[django.core.validators.MinLengthValidator], verbose_name='Religion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.classname'),
        ),
        migrations.AlterField(
            model_name='application',
            name='father_name',
            field=models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator], verbose_name='Father name'),
        ),
    ]
