# Generated by Django 3.1.5 on 2021-03-06 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_document_application'),
        ('preadmission', '0002_application_docs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='docs',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='student.document'),
        ),
    ]
