# Generated by Django 3.1.5 on 2021-03-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preadmission', '0003_auto_20210306_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_docs_verified',
            field=models.BooleanField(default=0, verbose_name='Is Docs Verified'),
        ),
    ]
